- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: maven setup
  include_role:
    name: common
    tasks_from: maven.yaml

- name: system service
  include_role:
    name: common
    tasks_from: systemd.yaml

- name: import data
  tags:
  - import
  community.mysql.mysql_db:
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.malli12.site
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: restarting the services
  tags:
  - import
  ansible.builtin.service:
    name: shipping
    state: started