
- name: disable module
  ansible.builtin.command: dnf module disable nginx -y

- name: enable module
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: starting the services
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: removing html file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the frontend files
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extracting the files
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copying the congif file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
  - restart nginx