  - name: installing mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: starting system services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setting root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1