  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: downloading the {{ component }} file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
      dest: /tmp/{{ component }}.zip
  
  - name: extract {{ component }} files
    ansible.builtin.unarchive: 
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes